services:
  trace-gen:
    build:
      context: ./trace-generator
      dockerfile_inline: |
        FROM python:3.7
        RUN --mount=type=bind,target=/tg \
            cp /tg/Pipfile.lock /Pipfile.lock &&\
            pip install pipenv && \
            pipenv requirements > requirements.txt && \
            pip install -r requirements.txt && \
            pip install spar && \
            mv /usr/local/lib/python3.7/site-packages/spar/data/samples /original-spar-1h-trace && \
            echo "Y" | pip uninstall spar && \
            echo "Y" | pip uninstall pipenv && \
            rm Pipfile.lock requirements.txt

    entrypoint: /bin/bash
    working_dir: /app
    tty: true
    volumes:
      - ./trace-generator:/app
      - ./generated:/generated
      - ./traces/alibaba/2018:/trace # Make downloaded alibaba trace avaliable (optional)

  mubench:
    image: "msvcbench/mubench@sha256:878ebc148159e1224334b0b09b7cf3393c1867c83782fa20f6a57714db7daf66"
    entrypoint: /bin/bash
    working_dir: /root/muBench
    tty: true
    volumes:
      - ./muBench-WorkModelParameters.json:/root/muBench/WorkModelParameters.json
      - ./muBench-K8sParameters.json:/root/muBench/K8sParameters.json
      - ./workload-extraction:/root/muBench/alibaba
      - ./muBench/WorkModelGenerator:/root/muBench/WorkModelGenerator
      - ./muBench/Deployers:/root/muBench/Deployers
      - ./generated:/generated
