# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

resources:
  cluster:
    node_count: 10
    nodes_total_cpu_cores: 100
    nodes_total_memory_mbytes: 160000
  node_target_utilization:
    mean_cpu: 0.2006
    mean_memory: 0.2708

node_roles:
  # the node that provides input dataset at '/dataset'
  # and provides svc-cell functions at '/internal-svc-functions'
  observer: node-2

benchmark:
  namespace: mubench
  cluster_domain: cluster
  dns_resolver: kube-dns.kube-system.svc.cluster.local
  scheduler: default-scheduler

  service_cell:
    image:
      name: lujoka/mub-cell
      version: 0.1.1
    ingress: false
    service_monitor: true
