apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-ee-benchmarking
  labels:
    benchmark: input
spec:
  template:
    spec:
      serviceAccountName: benchmark-sa
      initContainers:
      ################################## WORKMODEL GENERATION ##################################
      - name: workmodel-gen
        image: lujoka/mub-workmodel-gen:latest
        imagePullPolicy: Always
        command: ["/app/entrypoint.sh", "--config-file", "/config/WorkmodelParameters.json", "--log-level", "DEBUG"]
        volumeMounts:
        - name: dataset
          mountPath: "/dataset"
          readOnly: true
        - name: podshared
          mountPath: "/podshared"
          readOnly: false
        - name: workmodel-params
          mountPath: "/config"
          readOnly: true
      ################################## TEMPLATING K8S FILES ##################################
      - name: templater
        image: lujoka/mub-k8s-templater:latest
        imagePullPolicy: Always
        command: ["/app/entrypoint.sh", "--config-file", "/config/K8sParameters.json", "--log-level", "DEBUG", "-y"]
        volumeMounts:
        - name: dataset
          mountPath: "/dataset"
          readOnly: true
        - name: functions
          mountPath: "/InternalServiceFunctions"
          readOnly: true
        - name: podshared
          mountPath: "/podshared"
          readOnly: false
        - name: k8s-params
          mountPath: "/config"
          readOnly: true
      containers:
      ################################## RUNNING THE TRACE ##################################
      - name: runner
        image: lujoka/mub-csv-runner:latest
        imagePullPolicy: Always
        command: ["/app/entrypoint.sh", "--config-file", "/config/RunnerParameters.json"]
        volumeMounts:
        - name: dataset
          mountPath: "/dataset"
          readOnly: true
        - name: podshared
          mountPath: "/podshared"
          readOnly: true
        - name: runner-params
          mountPath: "/config"
        - name: result
          mountPath: "/result"
          readOnly: false
      restartPolicy: Never
      volumes:
        ## PVC linking to contents on node-2
        - name: dataset
          persistentVolumeClaim:
            claimName: dataset
        - name: functions
          persistentVolumeClaim:
            claimName: functions
        - name: result
          persistentVolumeClaim:
            claimName: result
        ## EmptyDIR to share the generated files between (init-)containers
        - name: podshared
          emptyDir: {}
        ## xyzParameters.json config files for all the steps
        - name: workmodel-params
          configMap:
            name: workmodel-params
        - name: k8s-params
          configMap:
            name: k8s-params
        - name: runner-params
          configMap:
            name: csv-runner-params
  backoffLimit: 1
