apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: benchmark-sa
  labels:
    benchmark: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-rolebinding
  labels:
    benchmark: controller
subjects:
  - kind: ServiceAccount
    name: benchmark-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
